<a href="https://colab.research.google.com/github/krish0195/ml_end_to-_end/blob/master/ml_workfile_processed_data_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Use to import pandas
import pandas as pd
#Use to import the file into google Colab drive
from google.colab import files
#Use to import io, which opens the file from the Colab drive
import io
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
from sklearn import metrics
from sklearn.metrics import roc_auc_score,roc_curve,classification_report,confusion_matrix
from sklearn.pipeline import Pipeline
from collections import Counter
from imblearn.over_sampling import SMOTE
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
from sklearn.preprocessing import StandardScaler
std_scale=StandardScaler()
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [ ]:
# This will open a widget when run that will enable you to browse the files on your local storage drive.
# the excel file after reshaping each to 1000 records:
uploaded = files.upload()


Saving Final_df.csv to Final_df.csv


In [ ]:

df_fulldata=pd.read_csv('Final_df.csv')



In [ ]:
#label encoding of tgt varaible
tgt_map = {    'Flexion_football':0,
               'Flexion_relaxed':1,
               'Flexion_stiffed':2,
               'Lateral_football':3,
               'Lateral_relaxed':4,
               'Lateral_stiffed':5
              }
df_fulldata["Direction"]=df_fulldata.Direction.map(tgt_map)
df_fulldata=df_fulldata.drop(columns=["time","Subject","Sr No"],axis=1)


In [ ]:
df_fulldata.head()

stern_mast_r  cleid_mas_r  cleid_occ_r  long_cap_sklc4_r  long_col_c1thx_r  long_col_c1c5_r  long_col_c5thx_r  trap_acr_r  splen_cerv_c3thx_r  semi_cap_sklc5_r  levator_scap_r  longissi_cap_sklc6_r  longissi_cerv_c4thx_r  iliocost_cerv_c5rib_r  rectcap_post_maj_r  rectcap_post_min_r  obl_cap_sup_r  obl_cap_inf_r  digastric_post_r  digastric_ant_r  Geniohyoid_r  Mylohyoid_Post_r  Mylohyoid_Ant_r  Stylohyoid_Lat_r  Stylohyoid_Med_r  Sterno_hyoid_r  SternoThyroid_r  Omo_hyoid_r  stern_mast_l  cleid_mast_l  cleid_occ_l  long_cap_sklc4_l  long_col_c1thx_l  long_col_c1c5_l  long_col_c5thx_l  trap_acr_l  splen_cerv_c3thx_l  semi_cap_sklc5_l  levator_scap_l  longissi_cap_sklc6_l  longissi_cerv_c4thx_l  iliocost_cerv_c5rib_l  rectcap_post_maj_l  rectcap_post_min_l  obl_cap_sup_l  obl_cap_inf_l  digastric_post_l  digastric_ant_l  Geniohyoid_l  Mylohyoid_Post_l  Mylohyoid_Ant_l  Stylohyoid_Lat_l  Stylohyoid_Med_l  Sterno_hyoid_l  SternoThyroid_l  Omo_hyoid_l  Direction
0     15.224083     7.329898     5.640508          4.864611          1.441753         1.441705          1.432433   63.239589            7.486504          8.959424       11.147425              4.716546               3.028918               3.019896            4.552728            2.566827       5.430573       6.848087          6.066963         3.807231      5.135560          2.806027         8.418082          1.028819          1.028841        3.070743         3.441343     3.970793     15.224083      7.329898     5.640508          4.864611          1.441753         1.441705          2.096794   63.239589            7.486504          8.959424       11.147425              4.716546               3.028918               3.019896            4.552728            2.566827       5.430573       6.848087          6.066963         3.807231      5.135560          2.806027         8.418082          1.028819          1.028841        3.070743         3.192654     3.836298          1
1     15.294100     7.383138     5.668919          4.845135          1.443353         1.443358          1.431789   64.153269            7.530222          8.956275       11.170654              4.683953               3.073223               3.091184            4.642744            2.599317       5.444150       6.846499          6.086064         3.634936      4.813947          2.750926         7.707358          1.026095          1.025724        3.120961         3.490565     4.057301     15.293540      7.382788     5.668730          4.846819          1.443342         1.443731          2.095949   64.152866            7.531798          8.957287       11.171136              4.683851               3.072262               3.090338            4.642719            2.599317       5.444150       6.846402          6.077234         3.634936      4.813947          2.750926         7.707358          1.026774          1.026485        3.120761         3.248781     3.929045          1
2     15.556113     7.572584     5.777622          4.761932          1.450133         1.450281          1.428901   67.604876            7.702682          8.941606       11.254600              4.555209               3.242777               3.359133            5.006113            2.736847       5.501278       6.839891          6.165724         2.991366      3.735757          2.528699         5.437963          1.014227          1.012177        3.321134         3.685095     4.407076     15.553191      7.570818     5.776619          4.771020          1.450073         1.452298          2.092197   67.602681            7.711268          8.946992       11.256895              4.554699               3.237829               3.354735            5.005968            2.736847       5.501278       6.839355          6.117054         2.991366      3.735757          2.528699         5.437963          1.017676          1.016033        3.320046         3.472213     4.304494          1
3     16.394531     8.130792     6.137115          4.464246          1.474171         1.474061     

In [ ]:
x=df_fulldata.drop(columns=['Direction'])
y=df_fulldata['Direction']
df_fulldata['Direction'].value_counts()

1    10000
2    10000
3    10000
4    10000
5    10000
0    10000
Name: Direction, dtype: int64

In [ ]:
# method 1:Feature selection:Corr() -Create correlation matrix
#corr_matrix = df_fulldata.corr().abs()
# Select upper triangle of correlation matrix
#upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))
# Find features with correlation greater than 0.95
#to_drop = [column for column in upper.columns if any(upper[column] > 0.95)]
#print("the no of columns to be removed=",len(to_drop))
# Drop features
#df_fulldata.drop(to_drop, axis=1, inplace=True)

In [ ]:
#method 2:Feature selection:PCA
#standard before doing PCA for reducing dimensions:
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
scalar.fit(x)
scaled_data = scalar.transform(x)


from sklearn.decomposition import PCA
pca = PCA(n_components=30)
pca.fit(scaled_data)
x_pca = pca.transform(scaled_data)
scaled_data.shape
x_pca.shape

(60000, 30)

#plots visuvalization:
plots=x

for i in plots.columns:
    plt.figure(figsize=(4,2))
    sns.kdeplot(plots[i])
    plt.axvline(x=plots[i].mean(),
            color='red')
    print("the mean is",plots[i].mean())
    print("the median is",plots[i].median())
    plt.axvline(x=plots[i].median(),
            color='blue',ls='--', lw=2.5)

    plt.show()


In [ ]:
#df=x.replace(0,np.NaN)
#df.isnull().sum().sort_values(ascending = False)/len(df)*100

In [ ]:
#Missing values inputation:
#numerical_cols=list(df.select_dtypes(exclude="object").columns)
#for i in df[numerical_cols]:
 #         df[i].replace(np.nan, df[i].median(),inplace=True)

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_pca, y, test_size = 0.20, stratify = y, random_state = 43,shuffle=True)

print("x_train shape is",x_train.shape)
print("y_train shape is",y_train.shape)

print("x_test shape is",x_test.shape)
print("y_test shape is",y_test.shape)

x_train shape is (48000, 30)
y_train shape is (48000,)
x_test shape is (12000, 30)
y_test shape is (12000,)


7 Models selected for train and test

In [ ]:
#Classification Metrics:

def prediction(x_train,y_train,x_test,y_test,y_train_predict,y_test_predict):

  #Accuracy Check of Train
  train_accuracy = metrics.accuracy_score(y_train,y_train_predict)
  print("The Train Accuracy:",round(train_accuracy,3))

# Accuracy Check of Test
  test_accuracy = metrics.accuracy_score(y_test,y_test_predict)
  print("The Test Accuracy",round(test_accuracy,4))


  return train_accuracy,test_accuracy

In [ ]:
#1)Logistic regressison

logisticRegr = LogisticRegression()
logisticRegr.fit(x_train, y_train)
y_train_predict = logisticRegr.predict(x_train)
y_test_predict = logisticRegr.predict(x_test)

print("the Train and Test accuracy of Logistic regressison")
lr_train_accuracy, lr_test_accuracy=prediction(x_train,y_train,x_test,y_test,y_train_predict,y_test_predict)

the Train and Test accuracy of Logistic regressison
The Train Accuracy: 0.95
The Test Accuracy 0.9517


In [ ]:
#2) Base Decision Tree
from sklearn.tree import DecisionTreeClassifier
DT = DecisionTreeClassifier(random_state= 101)
DT.fit(x_train,y_train)
y_train_predict = DT.predict(x_train)
y_test_predict = DT.predict(x_test)

print("the Train and Test accuracy of Decision Tree")
DT_train_accuracy, DT_test_accuracy=prediction(x_train,y_train,x_test,y_test,y_train_predict,y_test_predict)


the Train and Test accuracy of Decision Tree
The Train Accuracy: 0.995
The Test Accuracy 0.9816


In [ ]:
#3)RandomForestClassifier

from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(n_estimators=10,criterion='gini',max_depth=10,random_state=0)
rf_model.fit(x_train, y_train)
y_train_predict = rf_model.predict(x_train)
y_test_predict = rf_model.predict(x_test)

print("the Train and Test accuracy of RandomForestClassifier")
RF_train_accuracy, RF_test_accuracy=prediction(x_train,y_train,x_test,y_test,y_train_predict,y_test_predict)

the Train and Test accuracy of RandomForestClassifier
The Train Accuracy: 0.989
The Test Accuracy 0.9862


In [ ]:
#4) XG Boost calssifier
import xgboost as xgb
xgb_classifier = xgb.XGBClassifier()

xgb_classifier.fit(x_train, y_train)
y_train_predict = xgb_classifier.predict(x_train)
y_test_predict = xgb_classifier.predict(x_test)

print("the Train and Test accuracy of XG Boost calssifier ")
XGB_train_accuracy, XGB_test_accuracy=prediction(x_train,y_train,x_test,y_test,y_train_predict,y_test_predict)

the Train and Test accuracy of XG Boost calssifier 
The Train Accuracy: 0.996
The Test Accuracy 0.9842


In [ ]:
#5) KNN Algorithm
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=9)
knn.fit(x_train, y_train)
y_train_predict = knn.predict(x_train)
y_test_predict = knn.predict(x_test)

print("the Train and Test accuracy of KNN Algorithm ")
KNN_train_accuracy, KNN_test_accuracy=prediction(x_train,y_train,x_test,y_test,y_train_predict,y_test_predict)

the Train and Test accuracy of KNN Algorithm 
The Train Accuracy: 0.987
The Test Accuracy 0.9848


In [ ]:
#Comparison dataframe
index=["Accuracy"]
data = pd.DataFrame({'LR Train':[lr_train_accuracy],
                     'LR Test':[lr_test_accuracy],

                     'DT Train':[DT_train_accuracy],
                     'DT Test':[DT_test_accuracy],

                     'RF Train':[RF_train_accuracy],
                     'RF Test':[RF_test_accuracy],

                     'xgb Train':[XGB_train_accuracy],
                     'xgb Test':[XGB_test_accuracy],

                     'knn Train':[KNN_train_accuracy],
                     'knn Test':[KNN_test_accuracy],

                     },index=index)

print(round(data,4))



          LR Train  LR Test  DT Train  DT Test  RF Train  RF Test  xgb Train  xgb Test  knn Train  knn Test
Accuracy    0.9501   0.9517     0.995   0.9816    0.9892   0.9862     0.9959    0.9842     0.9872    0.9848


In [ ]:
#mean_accuracy_list
results_before_cv = pd.DataFrame({
    'Model': ['Logistic Regresssion', 'Decision Tree', 'Random Forest','K nearest',"xgb"],
    'Score_test': [lr_test_accuracy, DT_test_accuracy, RF_test_accuracy,KNN_test_accuracy,XGB_test_accuracy],
    'Score_train': [lr_train_accuracy, DT_train_accuracy, RF_train_accuracy,KNN_train_accuracy,XGB_train_accuracy]})
results_before_cv = results_before_cv.sort_values(by='Score_test', ascending=False)

results_before_cv = results_before_cv.set_index('Model')
results_before_cv.head(9)

Score_test  Score_train
Model                                        
Random Forest           0.986250     0.989187
K nearest               0.984750     0.987208
xgb                     0.984250     0.995938
Decision Tree           0.981583     0.995042
Logistic Regresssion    0.951667     0.950146

In [ ]:
#Since we have overfit issue we tried the below to remove the overfitting
#1- Cross validation:Best Model Selection:
#2-Feature selection
#3-L1 / L2 regularization (learning algorithm)
#4-Remove layers / number of units per layer (model)
#5-Dropout (model)

In [ ]:
                                                               #1.Cross validation

In [ ]:
 #1)CROSS VALIDATION-Logistic Regresssion

# Test
logisticRegr = LogisticRegression()
from sklearn.model_selection import cross_val_score
cv_score_lr_test = cross_val_score(logisticRegr, x_test, y_test, cv=5)
print(cv_score_lr_test)
mean_accuracy_lr = sum(cv_score_lr_test)/len(cv_score_lr_test)
mean_accuracy_lr = mean_accuracy_lr*100
mean_accuracy_lr = round(mean_accuracy_lr, 2)
print(mean_accuracy_lr)

#train
cv_score_lr_train = cross_val_score(logisticRegr, x_train, y_train, cv=5)
print(cv_score_lr_train)
mean_accuracy_lr_train = sum(cv_score_lr_train)/len(cv_score_lr_test)
mean_accuracy_lr_train = mean_accuracy_lr_train*100
mean_accuracy_lr_train = round(mean_accuracy_lr_train, 2)
print(mean_accuracy_lr_train)

[0.95       0.95041667 0.9575     0.94583333 0.95458333]
95.17
[0.95645833 0.94791667 0.95       0.95229167 0.95322917]
95.2


In [ ]:
 #2)CROSS VALIDATION-Decision Tree

 #Test
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
DT = DecisionTreeClassifier(random_state= 101)
cv_score_dt_test = cross_val_score(DT, x_test, y_test, cv=5)
print(cv_score_dt_test)
mean_accuracy_dt = sum(cv_score_dt_test)/len(cv_score_dt_test)
mean_accuracy_dt = mean_accuracy_dt*100
mean_accuracy_dt = round(mean_accuracy_dt, 2)
print(mean_accuracy_dt)


#Train

cv_score_dt_train = cross_val_score(DT, x_train, y_train, cv=5)
print(cv_score_dt_train)
mean_accuracy_dt_train = sum(cv_score_dt_train)/len(cv_score_dt_train)
mean_accuracy_dt_train = mean_accuracy_dt_train*100
mean_accuracy_dt_train = round(mean_accuracy_dt_train, 2)
print(mean_accuracy_dt_train)

[0.97958333 0.9725     0.98333333 0.97666667 0.98208333]
97.88
[0.98020833 0.9784375  0.98083333 0.97927083 0.980625  ]
97.99


In [ ]:
 #3)CROSS VALIDATION-Random Forest

#Test
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(n_estimators=10,criterion='gini',max_depth=10,random_state=0)
cv_score_rf_test = cross_val_score(rf_model, x_test, y_test, cv=5)
print(cv_score_rf_test)
mean_accuracy_rf = sum(cv_score_rf_test)/len(cv_score_rf_test)
mean_accuracy_rf = mean_accuracy_rf*100
mean_accuracy_rf = round(mean_accuracy_rf, 2)
print(mean_accuracy_rf)


#Train
cv_score_rf_train = cross_val_score(rf_model, x_train, y_train, cv=5)
print(cv_score_rf_train)
mean_accuracy_rf_train = sum(cv_score_rf_train)/len(cv_score_rf_train)
mean_accuracy_rf_train = mean_accuracy_rf_train*100
mean_accuracy_rf_train = round(mean_accuracy_rf_train, 2)
print(mean_accuracy_rf_train)


[0.98583333 0.98458333 0.9875     0.98333333 0.98833333]
98.59
[0.98416667 0.98302083 0.98677083 0.98302083 0.985     ]
98.44


In [ ]:
 #4)CROSS VALIDATION-xgb Classifier

#test
import xgboost as xgb
xgb_classifier = xgb.XGBClassifier()
cv_score_xg_test = cross_val_score(xgb_classifier, x_test, y_test, cv=5)
print(cv_score_xg_test)
mean_accuracy_xg = sum(cv_score_xg_test)/len(cv_score_xg_test)
mean_accuracy_xg = mean_accuracy_xg*100
mean_accuracy_xg = round(mean_accuracy_xg, 2)
print(mean_accuracy_xg)

#Train
cv_score_xg_train = cross_val_score(xgb_classifier,x_train, y_train, cv=5)
print(cv_score_xg_train)
mean_accuracy_xg_train = sum(cv_score_xg_train)/len(cv_score_xg_train)
mean_accuracy_xg_train = mean_accuracy_xg_train*100
mean_accuracy_xg_train = round(mean_accuracy_xg_train, 2)
print(mean_accuracy_xg_train)

[0.98458333 0.9825     0.98791667 0.985      0.99      ]
98.6
[0.98208333 0.9825     0.98427083 0.98239583 0.98291667]
98.28


In [ ]:
 #5)CROSS VALIDATION-KNeighborsClassifier
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=9)
cv_score_kn = cross_val_score(knn, x_test, y_test, cv=5)
print(cv_score_kn)
mean_accuracy_kn = sum(cv_score_kn)/len(cv_score_kn)
mean_accuracy_kn = mean_accuracy_kn*100
mean_accuracy_kn = round(mean_accuracy_kn, 2)
print(mean_accuracy_kn)

#train
cv_score_kn_train = cross_val_score(knn, x_train, y_train, cv=5)
print(cv_score_kn_train)
mean_accuracy_kn_train = sum(cv_score_kn_train)/len(cv_score_kn_train)
mean_accuracy_kn_train = mean_accuracy_kn_train*100
mean_accuracy_kn_train = round(mean_accuracy_kn_train, 2)
print(mean_accuracy_kn_train)




[0.97666667 0.97458333 0.97708333 0.97458333 0.97875   ]
97.63
[0.98291667 0.98104167 0.98364583 0.98302083 0.98322917]
98.28


# list of models for cross validation:
models = [logisticRegr,DT, rf_model,xgb_classifier,knn]
mean_accuracy_list = []


def compare_models_cross_validation():

  for model in models:
    cv_score = cross_val_score(model, x,y, cv=5)
    mean_accuracy = sum(cv_score)/len(cv_score)
    mean_accuracy = mean_accuracy*100
    mean_accuracy = round(mean_accuracy, 2)
    mean_accuracy_list.append(mean_accuracy)

    headers = ["Model", "Scores", "Mean"]
    data = [[model, cv_score, mean_accuracy]]
    dfCatb_scores_tg = pd.DataFrame(data, columns=headers)
    dfCatb_scores_tg.head()
    print('Cross Validation accuracies for ', model, '=  ', cv_score)
    print('Accuracy % of the ', model, mean_accuracy)
    print('----------------------------------------------')
    #compare_models_cross_validation()




In [ ]:
#mean_accuracy_list
results = pd.DataFrame({
    'Model': ['Logistic Regresssion', 'Decision Tree', 'Random Forest','K nearest',"xgb"],
    'Score_test': [mean_accuracy_lr, mean_accuracy_dt, mean_accuracy_rf,mean_accuracy_kn,mean_accuracy_xg],
    'Score_train': [mean_accuracy_lr_train, mean_accuracy_dt_train, mean_accuracy_rf_train,mean_accuracy_kn_train,mean_accuracy_xg_train]})
result_df = results.sort_values(by='Score_test', ascending=False)

result_df = result_df.set_index('Model')
result_df.head(9)

NameError: ignored

param_grid = { "criterion" : ["gini", "entropy"], "min_samples_leaf" : [1, 5, 10, 25, 50, 70], "min_samples_split" : [2, 4, 10, 12, 16, 18, 25, 35], "n_estimators": [100, 400, 700, 1000, 1500]}

from sklearn.model_selection import GridSearchCV
rf = RandomForestClassifier(n_estimators=100, max_features='auto', oob_score=True, random_state=1, n_jobs=-1)
clf = GridSearchCV(estimator=rf, param_grid=param_grid, n_jobs=-1)
clf.fit(x_train, y_train)
clf.bestparams